### PR TITLE
Add hasTombstone property

### PR DESCRIPTION
**Pull request by acoburn**
Related to: https://jira.duraspace.org/browse/FCREPO-2123

### CODE REVIEW

**Comment by ajs6f** [comment]
What's the expected domain of this?

**Comment by acoburn** [comment]
@ajs6f I left the domain undefined because in practice the domain is a deleted `fedora:Resource`. I certainly have no idea what the range would be.

**Comment by ajs6f** [comment]
I'm not sure I like the idea of a predicate of this sort. Isn't it basically more of an HTTP header?

**Comment by acoburn** [comment]
@ajs6f I don't disagree with you. The issue from my perspective is this: on a deleted resource, the following HTTP header is returned:

    GET /rest/deleted-resource

    HTTP/1.1. 410 GONE
    Link: <http://localhost:8080/rest/deleted-resource/fcr:tombstone>; rel="hasTombstone"

Given that IANA doesn't define `hasTombstone`, the meaning of that relation is ambiguous. What I've seen with other projects (e.g. Linked Data Notifications) is for link relations that are not part of IANA a fully qualified URI is used in the `rel="..."` statement. This PR is an attempt to fully qualify that URI.

**Comment by acoburn** [comment]
We may want to reopen this later, but for now it should wait on the API specification effort.

**Pull request closed without merging**
