### PR TITLE
Update index generation to be templated for additional ontologies

### PR DESCRIPTION
**Pull request by awoods**
Resolves: https://jira.duraspace.org/browse/FCREPO-1784

### CODE REVIEW

**Comment by acoburn** [comment]
Is the intention that the resulting HTML will go here: http://fedora.info/ ?
Perhaps we can dress it up a bit.

**Comment by awoods** [comment]
I am totally into a dress-up.

**Comment by acoburn** [comment]
Feel free to copy from here: https://github.com/fcrepo4/ontology/blob/master/owl2html.xsl

**Comment by acoburn** [comment]
Merged via 8d4322742dafc52b4c3817156ff11269f39b4b2d

**Pull request closed without merging**
