### PR TITLE
remove JCR-, MODE- and ISPN-related data properties

### PR DESCRIPTION
**Pull request by acoburn**
See: https://jira.duraspace.org/browse/FCREPO-1819

### CODE REVIEW

**Comment by ajs6f** [comment]
A giant :-1:  to this.

**Comment by ajs6f** [comment]
just a typo

**Comment by acoburn** [comment]
@ajs6f there are a lot of properties removed here -- can you just go over them with a fine-toothed comb to make sure I'm not being over-zealous?

**Comment by ajs6f** [comment]
I have looked through them, and I am happy with them gone. Those relating to clustering should never have been there (we have no design for that in the API) and the others are entirely JCR-specific. Terminate with extreme prejudice.

**Comment by acoburn** [comment]
@ajs6f if you're happy with this as it stands, I'd like to add one more commit to update the lastModified date.

**Comment by ajs6f** [comment]
Sure, but what do you mean my "update"? You mean change it to a different property?

**Comment by acoburn** [comment]
@ajs6f I actually meant updating the values of `owl:versionInfo` and `owl:priorVersion`. See the add-on commit.

**Comment by ajs6f** [comment]
Oh, yeah-yeah.

**Pull request merged**
